#pragma once

#include <lvgl.h>

#if defined(CONFIG_PROSPECTOR_STATUS_SCREEN_DEFAULT)

LV_FONT_DECLARE(Symbols_Semibold_32);
LV_FONT_DECLARE(FG_Medium_20);
LV_FONT_DECLARE(FR_Regular_48);
LV_FONT_DECLARE(FR_Thin_48);

#elif defined(CONFIG_PROSPECTOR_STATUS_SCREEN_ROUNDED_GRID)

LV_FONT_DECLARE(Symbols_Semibold_32);
LV_FONT_DECLARE(Symbols_Semibold_28);
LV_FONT_DECLARE(Symbols_Regular_28);
LV_FONT_DECLARE(Symbols_Bold_26);
LV_FONT_DECLARE(PPF_NarrowThin_64);

#elif defined(CONFIG_PROSPECTOR_STATUS_SCREEN_WIND_MAP)

LV_FONT_DECLARE(Symbols_Semibold_32);
LV_FONT_DECLARE(Symbols_Regular_28);
LV_FONT_DECLARE(FR_Regular_30);
LV_FONT_DECLARE(FR_Regular_36);

#endif
